namespace ManualWindow.WindowMessageEnums
{
    public enum SysColorIndex
    {
        SCROLLBAR = 0,
        BACKGROUND = 1,
        DESKTOP = 1,
        ACTIVECAPTION = 2,
        INACTIVECAPTION = 3,
        MENU = 4,
        WINDOW = 5,
        WINDOWFRAME = 6,
        MENUTEXT = 7,
        WINDOWTEXT = 8,
        CAPTIONTEXT = 9,
        ACTIVEBORDER = 10,
        INACTIVEBORDER = 11,
        APPWORKSPACE = 12,
        HIGHLIGHT = 13,
        HIGHLIGHTTEXT = 14,
        BTNFACE = 15,
        FACE_3D = 15,
        BTNSHADOW = 16,
        SHADOW_3D = 16,
        GRAYTEXT = 17,
        BTNTEXT = 18,
        INACTIVECAPTIONTEXT = 19,
        BTNHIGHLIGHT = 20,
        HIGHLIGHT_3D = 20,
        HILIGHT_3D = 20,
        BTNHILIGHT = 20,
        DKSHADOW_3D = 21,
        LIGHT_3D = 22,
        INFOTEXT = 23,
        INFOBK = 24,
        HOTLIGHT = 26,
        GRADIENTACTIVECAPTION = 27,
        GRADIENTINACTIVECAPTION = 28,
        MENUHILIGHT = 29,
        MENUBAR = 30,
    }
}
